### ISSUE TITLE
这个web端运行起来了，但是这个注册登陆按钮好像是没有触发接口的

### ISSUE THREAD

**Issue by silas0277** [ceresOPA/Computer-Vision-System#1]
这个web端运行起来了，但是这个注册登陆按钮好像是没有触发接口的

**Comment by ceresOPA** [comment]
不好意思，一直没看到。是有接口的，后端有没有跑起来？还要连接MySQL数据库，这一点之前没提，User表的model文件在server的目录下有给出，可以进行ORM映射自动生成数据表。
![image](https://user-images.githubusercontent.com/44893804/204260596-324c92ec-7875-47ec-8d43-3bac9cf8dc21.png)

**Comment by huyunlei** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您发来的邮件已经收到，我会尽快给您回复。

**Comment by huyunlei** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您发来的邮件已经收到，我会尽快给您回复。
